require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'app/definitions/**/*'

Style/Documentation:
  # Skips checking to make sure top level modules / classes have a comment.
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  # Use nested module style for consistency and so that modules don't need to be declared separately.
  EnforcedStyle: nested

Style/MixinUsage:
  Enabled: false

Layout/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/support/omniauth_macros.rb'
    - 'app/presenters/nav_presenter.rb'

Rails/SkipsModelValidations:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/application_controller.rb'
