require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
  Exclude:
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'app/definitions/**/*'
    - 'vendor/**/*' # For CircleCI.

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'app/views/**/*'

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Rails/OutputSafety:
  Exclude:
    - 'app/views/**/*'
    
Rails/SkipsModelValidations:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  # Use compact module style for consistency and better indendation.
  EnforcedStyle: compact
  Exclude:
    - 'swagger/**/*'

Style/Documentation:
  # Skips checking to make sure top level modules / classes have a comment.
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false
