require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'app/definitions/**/*'
    - 'vendor/**/*' # For CircleCI.

Style/Documentation:
  # Skips checking to make sure top level modules / classes have a comment.
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  # Use compact module style for consistency and better indendation.
  EnforcedStyle: compact
  Exclude:
    - 'swagger/**/*'

Style/MixinUsage:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Rails/SkipsModelValidations:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
