version: '3.7'

services:
  # PostgresSQL option.
  # db:
  #   image: 'postgres:12.2-alpine'
  #   volumes:
  #     - 'db:/var/lib/postgresql/data'
  #   env_file:
  #     - '.env'

  # MySQL option.
  db:
    image: 'mysql:8.0.19'
    restart: always
    volumes:
      - 'db:/var/lib/mysql'
    env_file:
      - '.env'
    ports:
      - '3307:3306'

  # SQL Server option.
  # db:
  #   image: microsoft/mssql-server-linux:2017-latest
  #   volumes:
  #     - 'db:/var/lib/sql_server'
  #   env_file:
  #     - '.env'
  #   ports:
  #     - '3307:1433'

  redis:
    image: 'redis:6.0.1-alpine'
    command: redis-server --requirepass yourpassword
    depends_on:
      - redis_helper
    sysctls:
      # This removes 'WARNING: /proc/sys/net/core/somaxconn is set to the lower value of 128'
      # Explanation of what this setting does: https://groups.google.com/d/msg/redis-db/ftmlTjEPv98/HwkJguxTCwAJ
      net.core.somaxconn: '511'
    volumes:
      - 'redis:/data'

  # Fix Redis 'WARNING you have Transparent Huge Pages (THP) support'.
  # From: https://stackoverflow.com/a/58090841
  # More details: https://easyengine.io/tutorials/redis/
  redis_helper:
    image: busybox
    command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    privileged: true

  app:
    depends_on:
      - db
      - redis
      - webpacker
      - webdriver_chrome
    build: .
    # 1) Remove any existing server process in case of dirty shutdown, with -f in case the file doesn't exist.
    # 2) if `bundle check` indicates it's needed, `bundle install` here rather than in Dockerfile,
    #    so that we can cache its result in the bundle_cache container.
    # 3) Start server.
    command: ./script/start_rails.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      # We cache the bundle so that we don't re-download every gem on any change to the Gemfile.
      - bundle_cache:/bundle
    environment:
      - SELENIUM_HEADLESS_URL=http://webdriver_chrome:4444/wd/hub
      - SELENIUM_VISIBLE_URL=http://webdriver_chrome_debug:4444/wd/hub
      - SELENIUM_APP_HOST=http://app:3000
      - BUNDLE_PATH=/bundle/vendor
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    env_file:
      - '.env'

  webdriver_chrome:
    image: selenium/standalone-chrome:3.141.0
    volumes:
      - '.:/app'
      - bundle_cache:/bundle

  webdriver_chrome_debug:
    image: selenium/standalone-chrome-debug:3.141.0
    ports:
      - 5900:5900 # Port for remote connection via vnc.
    volumes:
      - '.:/app'
      - bundle_cache:/bundle

  bundle_cache:
    # BusyBox combines tiny versions of many common UNIX utilities into a single small executable.
    image: busybox
    volumes:
      - '.:/bundle_cache'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: ./script/start_sidekiq.sh
    volumes:
      - '.:/app'
      - bundle_cache:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
    env_file:
      - '.env'

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - '.:/app'
      - bundle_cache:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    env_file:
      - '.env'

volumes:
  bundle_cache:
  redis:
  db:
