version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@4.1.0
  heroku: circleci/heroku@1.0.1

jobs:
  hamllint:
    parallelism: 1
    docker:
      - image: cimg/ruby:3.0.0-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run haml-lint
          command: bundle exec haml-lint app/views
  rubocop:
    parallelism: 1
    docker:
      - image: cimg/ruby:3.0.0-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.0.0-node
      - image: circleci/mysql:8.0.19
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: circle_ci
      - image: selenium/standalone-chrome:3.141.0
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
      DB_DATABASE: circle_ci
      DB_USERNAME: root
      DB_HOST: "127.0.0.1"
      HEADLESS_CHROME_URL: http://localhost:4444/wd/hub
      CAPYBARA_APP_HOST: http://localhost:3001
      SPEC_RETRIES: 3
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      # CHROMIUM_PATH: /usr/bin/chromium-browser
      GROVER_NO_SANDBOX: true
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Install chromium browser
          command: |
            sudo apt-get -y update
            sudo apt-get -y install chromium-browser
      # - run:
      #     name: Install Chromium
      #     command: npm i chromium
      # - run:
      #     name: Install Puppeteer skip Chromium
      #     command: npm i puppeteer
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: TMP make sure puppeteer installed
          command: yarn info puppetter
      - run:
          name: TMP chromium info
          command: which chromium-browser
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-results/rspec
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec/rspec.xml \
                              --format progress \
                              -- \
                              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results/rspec
      - store_artifacts:
          path: coverage
workflows:
  version: 2
  checks:
    jobs:
      - hamllint
      - rubocop
      - test
      - heroku/deploy-via-git:
          requires:
            - hamllint
            - rubocop
            - test
          filters:
            branches:
              only: master
