default: &default
  adapter: redis
  url: <%= "redis://redis:#{ENV['REDIS_PORT']}/1" %>
  password: <%= ENV['REDIS_PASSWORD'] %>

development:
  <<: *default
  channel_prefix: murfin_method_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: murfin_method_production
