---

default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  reconnect: false
  pool: 50
  username: <%= ENV['DB_USERNAME'] || ENV['MYSQL_USER'] %>
  password: <%= ENV['DB_PASSWORD'] || ENV['MYSQL_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] || 'db' %>
  socket: /var/run/mysqld/mysqlx.sock

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>_development

test:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'db_test' %>
  database: <%= ENV['DB_DATABASE'] %>_test<%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'db_test' %>
  database: <%= ENV['DB_DATABASE'] %>_test

production:
  <% if ENV['CLEARDB_DATABASE_URL'] %>
    # For Heroku.
    adapter: mysql2
    encoding: utf8mb4
    database: murfin_method_production
    url: <%= ENV['CLEARDB_DATABASE_URL'] %>
  <% else %>
    <<: *default
    database: <%= ENV['DB_DATABASE'] %>_production
  <% end %>
